"""updating users table

Revision ID: 5398a22cf5b9
Revises: 7ed64833756b
Create Date: 2022-07-09 19:27:00.525537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5398a22cf5b9'
down_revision = '7ed64833756b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img_url')
    # ### end Alembic commands ###
